# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "json", "~> 2.5"

gem "tty-prompt", "~> 0.23.1"

gem "tty-table", "~> 0.12.0"

gem "tty-box", "~> 0.7.0"

gem "rainbow", "~> 3.0"

gem "artii", "~> 2.1"

gem "tty-spinner", "~> 0.9.3"

gem "colorize", "~> 0.8.1"
